services:
  # todo: upload shortie image to dockerhub once done development
  # then use it here
  db:
    image: postgres
    container_name: shortie-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USER} -d ${APP_DB_NAME}"]
      interval: 1s
volumes:
  postgres_data: