services:
  nginx:
    image: nginx:1.29.4-alpine
    container_name: shortie-nginx
    ports:
      - "80:80"
      - "81:81"
    restart: unless-stopped
    volumes:
      - dashboard_dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - dashboard
      - api

  api:
    container_name: shortie-api
    # todo: upload shortie image to dockerhub and use it here
    restart: unless-stopped
    build:
      dockerfile: api.dockerfile
    depends_on:
      - db
    environment:
      APP_DB_URL: jdbc:postgresql://db:5432/${APP_DB_NAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_DB_USER: ${APP_DB_USER}
      APP_ID_ALPHABET: ${APP_ID_ALPHABET}
      APP_ID_MIN_LENGTH: ${APP_ID_MIN_LENGTH}
      APP_AUTH_SECRET: ${APP_AUTH_SECRET}
      APP_AUTH_ISSUER: ${APP_AUTH_ISSUER}
      APP_AUTH_AUDIENCE: ${APP_AUTH_AUDIENCE}
      APP_AUTH_REALM: ${APP_AUTH_REALM}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      APP_ALLOW_CORS: ${APP_ALLOW_CORS}

  dashboard:
    container_name: shortie-dashboard
    restart: no
    build:
      dockerfile: dashboard.dockerfile
    environment:
      # remember about trailing slash
      API_URL: http://localhost/api/
    volumes:
      - dashboard_dist:/dist

  db:
    image: postgres
    container_name: shortie-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_DB_USER} -d ${APP_DB_NAME}" ]
      interval: 1s
volumes:
  postgres_data:
  dashboard_dist: