ktor:
  application:
    modules:
      - com.kborowy.shortie.ApplicationKt.app
  deployment:
    port: 8080
    proxyPort: ${APP_API_PROXY_PORT:80}
    shutdownGracePeriod: 2000
    shutdownTimeout: 3000

  allowCORS: ${APP_ALLOW_CORS:false}

database:
  url: ${APP_DB_URL}
  user: ${APP_DB_USER}
  password: ${APP_DB_PASSWORD}

hash:
  minLength: ${APP_ID_MIN_LENGTH:3}
  alphabet: ${APP_ID_ALPHABET}

auth:
  secret: ${APP_AUTH_SECRET}
  issuer: ${APP_AUTH_ISSUER:shortie-api}
  audience: ${APP_AUTH_AUDIENCE:shortie-user}
  realm: shortie-dashboard

admin:
  password: ${APP_ADMIN_PASSWORD}